exec-once = waybar &

# =========================
# Core session startup
# =========================

# DBus (required for many apps)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# =========================
# Portal (Wayland apps support)
# =========================
exec-once = /usr/lib/xdg-desktop-portal-hyprland

# =========================
# Authentication agent
# =========================
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# =========================
# Notification daemon (lightweight)
# =========================
exec-once = mako

# =========================
# Network applet (optional but useful)
# =========================
#exec-once = nm-applet
#exec-once = lan-mouse --frontend cli
# =========================
# Clipboard manager (lightweight)
# =========================
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# =========================
# Idle + power management (IMPORTANT for battery)
# =========================
exec-once = hypridle

# =========================
# Optional: wallpaper (very light)
# =========================
# exec-once = swaybg -i ~/wallpapers/wall.jpg -m fill
exec-once = hyprpaper

exec-once = aw-qt
